### ISSUE TITLE
放在外面主循环里运行的代码得不到更新，也就不能热重载了😂

### ISSUE THREAD

**Issue by hangj** [cj1128/hot-reload-c#2]
放在外面主循环里运行的代码得不到更新，也就不能热重载了😂

_Originally posted by @cj1128 in https://github.com/cj1128/hot-reload-c/issues/1#issuecomment-864493408_

可以通过 signal 触发 reload render.dylib  
main.c 里面注册一个 signal(SIGUSR1, reload)  
每次 build 完就给进程发一个 signal  
`ps -ef | grep dist/main.out| grep -v grep| awk '{print $2}'|xargs kill -s SIGUSR1 `

**Comment by cj1128** [comment]
嗯，这样是可以的。

这次其实主要是想演示怎么去热重载，没有考虑效率。

真正的工程中，可以使用你说的 Signal，也可以直接比对时间戳，时间戳新就 Load。
